sudo: required

services:
  - docker

# Build test version of vue test
before_install:
  - docker build -t jaychangha/vue-test -f ./client/Dockerfile.dev ./client

# Run test cases
script:
  - docker run jaychangha/vue-test npm run test

# If test is successful
after_success:
  # Build production version of all projects
  - docker build -t jaychangha/template-client ./client
  - docker build -t jaychangha/template-nginx ./nginx
  - docker build -t jaychangha/template-server ./server
  - docker build -t jaychangha/template-worker ./worker

  # Login to the docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to docker hub
  - docker push jaychangha/template-client
  - docker push jaychangha/template-nginx
  - docker push jaychangha/template-server
  - docker push jaychangha/template-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: docker-multi-services-template
  env: DockerMultiServicesTemplate-env

  # Go to AWS S3 to get bucket name(at same region)
  bucket_name: elasticbeanstalk-us-west-2-553326145434

  # The path in above bucket
  bucket_path: docker-multi

  # Only try to run the deployment when the branch that was pushed or build up on travis
  on:
    branch: master

  acccess_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY