apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  # 在 GKE 中 ingress-controller 只能連向為 NodePort 或 LoadBalance 的 Service 
  # type: ClusterIP
  type: NodePort
  selector:
    component: front-end
  ports:
  - port: 3000
    targetPort: 8080
